module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond',
    "Pale"
];

module.exports.secondaryDescriptors = [
    "Crimson ",
    "Olive ",
    "Periwinkle ",
    " ",
    "Flourescent ",
    "Ash ",
    "Brittle ",
    "Floating ",
    "Dark ",
    "Light ",
    "Deserted ",
    "Bloodshot ",
    "Sparkling ",
    "Red "
];

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow'
];
